<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="AppServicios.Application\" />
    <Folder Include="AppServicios.Presentation\" />
    <Folder Include="AppServicios.Domain\" />
    <Folder Include="AppServicios.Infrastructure\" />
  </ItemGroup>

</Project>
